#!/bin/bash

YUM=/usr/bin/yum
HOME_DIR=/home/rich
BOOTSTRAP_DIR=/tmp/bootstrap
PROD_DIR=$HOME_DIR/data/docs/fiveguys/prod
DEV_DIR=$HOME_DIR/data/docs/fiveguys/dev-mjipeo
LOG_DIR=$HOME_DIR/data/logs/fiveguys
RPM=/bin/rpm
YUM=/usr/bin/yum
MAKE=/usr/bin/make
CHKCONFIG=/sbin/chkconfig
SERVICE=/sbin/service
PYTHON=/usr/local/bin/python2.7
EASY_INSTALL=/usr/local/bin/easy_install-2.7
PIP=/usr/local/bin/pip-2.7
SUPERVISORCTL=/usr/local/bin/supervisorctl
NPM=/usr/local/bin/npm

sudo $YUM install -y zsh git

cd ~
git clone https://github.com/robbyrussell/oh-my-zsh ~/.oh-my-zsh
git clone https://github.com/mjipeo/dotfiles.git ~/.dotfiles

exit;


sudo $YUM install -y zsh git


# Install Python 2.7
cd /tmp
sudo $YUM groupinstall -y "Development tools"
sudo $YUM install -y zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel readline-devel tk-devel
wget http://python.org/ftp/python/2.7.3/Python-2.7.3.tar.bz2 --no-check-certificate
tar xf Python-2.7.3.tar.bz2
cd Python-2.7.3
./configure --prefix=/usr/local
make && sudo $MAKE altinstall

# Install Distribute & PIP
cd /tmp
wget http://pypi.python.org/packages/source/d/distribute/distribute-0.6.35.tar.gz --no-check-certificate
tar xf distribute-0.6.35.tar.gz
cd distribute-0.6.35
sudo $PYTHON setup.py install
sudo $EASY_INSTALL pip

# Install Virtualenv
cd /tmp
sudo $PIP install virtualenv
sudo $PIP install virtualenvwrapper

export WORKON_HOME=$HOME_DIR/.virtualenvs
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python2.7
export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv-2.7
source /usr/local/bin/virtualenvwrapper.sh

mkvirtualenv --distribute --no-site-package fiveguys
workon fiveguys

# (Master Only) Recompile VIM with ruby support
sudo $YUM install -y hg
cd /tmp
hg clone https://vim.googlecode.com/hg/ vim
cd vim
./configure --enable-pythoninterp --enable-rubyinterp
make
sudo $MAKE install

# (Master Only) Install Node.js & NPM
cd /tmp
wget http://nodejs.org/dist/v0.10.21/node-v0.10.21.tar.gz
tar xfz node-v0.10.21.tar.gz
cd node-v0.10.21
./configure --prefix=/usr/local
make && sudo $MAKE install

# Install Supervisor
# ------------------
sudo $EASY_INSTALL supervisor
sudo cp $BOOTSTRAP_DIR/supervisord.conf /etc/
sudo cp $BOOTSTRAP_DIR/supervisord /etc/init.d/
sudo $CHKCONFIG supervisord on
sudo $SERVICE supervisord start

